apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: latinoware-scraper
  namespace: latinoware-io
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: latinoware-scraper
    spec:
      containers:
      - image: lvlds/latinoware-scraper
        imagePullPolicy: Always
        name: latinoware-scraper
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_PORT_27017_TCP_ADDR
            value: "latinoware-mongo"
          - name: MONGO_PORT_27017_TCP_PORT
            value: "27017"