apiVersion: v1
kind: PersistentVolume
metadata:
  name: latinoware-mongo-data-nfs
  namespace: latinoware-io
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs-server
    path: /exports/mongo-data/latinoware-mongo