apiVersion: v1
kind: PersistentVolume
metadata:
  name: latinoware-mongo-data-nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.3.248.103
    path: /exports/mongo-data/latinoware-mongo