apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: latinoware-mongo-data-nfs
  namespace: latinoware-io
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi