apiVersion: v1
kind: Service
metadata:
  labels:
    app: latinoware-mongo
  name: latinoware-mongo
  namespace: latinoware-io
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: latinoware-mongo
